TARGET = w4_isr
WORKLOAD_C_SOURCES = Core/Src/main.c Core/Src/stm32h7rsxx_it.c
WORKLOAD_EXTRA_HAL = ../common/hal_extra/Src/stm32h7rsxx_hal_tim.c ../common/hal_extra/Src/stm32h7rsxx_hal_tim_ex.c
include ../common/Makefile.common
